### ISSUE TITLE
Backups tab not shown unless there is a single LXC existing

### ISSUE THREAD

**Issue by djismgaming** [ich777/unraid-lxc-plugin#14]
Hi, just came across this "issue". 

- The Backups tab is not shown unless there is a single LXC existing. 
- And I can only see backups for existing LXCs with same name as a backup taken previously. 

If I don't have a `adguardhome` LXC, I will not see the previous, existing, backups for `adguardhome`. I have to create an LXC named `adguardhome` to see the backups.

Is that expected?

**Comment by ich777** [comment]
> * The Backups tab is not shown unless there is a single LXC existing.
> 
> * And I can only see backups for existing LXCs with same name as a backup taken previously.

Yes, that's how I designed the plugin and the Backup function which is by the way pretty unique to unRAID.

> If I don't have a `adguardhome` LXC, I will not see the previous, existing, backups for `adguardhome`.

Exactly, at least not in the GUI, it works almost the same way as snapshots with the exception that a Backup is not deleted if you delete the container itself, because it's a backup.

> I have to create an LXC named `adguardhome` to see the backups.

No, that's not entirely true you always can restore a Backup from the command line.
I've completely wrote the Backup function for unRAID from scratch and you can get a full list of commands and what's possible when you issue `lxc-autobackup --help` from the command line.

If you've configured the Backup function within the plugins settings (so to speak globally) then you can do something like:
`lxc-autobackup -r adguardhome adguardhomenew`
and it will create a new container with the name `adguardhomenew` from the latest `adguardhome` backup that it finds in your backup folder.

I'm not too sure if I would really like to display all old backups in the GUI because this can get very confusing.

On another topic, I hope you know [my container archives](https://github.com/ich777?tab=repositories&q=lxc&type=&language=&sort=) and how to install them?
EDIT: You can find a brief description how to install them [here](https://github.com/ich777/unraid_lxc_pihole?tab=readme-ov-file#step-1-install-container-archive), it boils down to download the RAW template file to `/tmp` on your server and visit `http://UNRAIDIP/LXCAddTemplate`

**Comment by ich777** [comment]
@djismgaming did my post explain everything?

**Comment by ich777** [comment]
Closing this issue due to no further response, if you have any other questions feel free to open up a new Issue or post directly on the Forums since it seems to me that you are more active there.

**Comment by djismgaming** [comment]
Yes @ich777 , all has been explained! Thanks so much for this. Also, thanks for this amazing plug in. 👌

And the template archive reminds me of the helper scripts for Proxmox! 😍
